export type IChallenge = {
    id:string;
    title:string;
    category:string;
    startDate:string;
    endDate:string;
    uploadStartTime:string;
    uploadEndTime:string;
    participantsLimit:number;
    description:string;
    authMethod:string;
    mainImage:string;
    successImage:string;
    failImage:string;
    userNickname:string;
    participants:number;
    isJoined:boolean;
    state:string;
    prize:number;
    hasCheckedInToday:boolean;
    userChallengeId:string;
    isLimited:boolean;
}